version: '3.7'

services:
    php:
      build:
        context: .
        args:
          - http_proxy=${PROXY}
          - https_proxy=${PROXY}
      links:
        - db
      volumes:
        - "./:/var/www"
      ports:
        - "80:80"
      environment:
        - http_proxy=${PROXY}
        - https_proxy=${PROXY}
        - APP_ENV=${APP_ENV}
        - APP_DEBUG=1
        - APP_SECRET=${APP_SECRET}
        - DATABASE_URL=${DATABASE_URL}
      working_dir: "/var/www"
      deploy:
        resources:
          limits:
                memory: 100M
      depends_on:
        - db

    db:
      image: mysql:8.0
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
      ports:
        - "3306:3306"
      volumes:
        - "./.data/db:/var/lib/mysql"
      environment:
        - "MYSQL_ROOT_PASSWORD=123"
        - "MYSQL_USER=appuser"
        - "MYSQL_PASSWORD=userPass"
        - "MYSQL_DATABASE=app"

    mailcatcher:
      image: schickling/mailcatcher
      ports:
        - "1080:1080"