version: '3.7'

services:
    php:
      build:
        context: .
      links:
        - db
      volumes:
        - "./:/var/www"
      ports:
        - "80:80"
      environment:
        - APP_ENV=${APP_ENV}
        - APP_DEBUG=1
        - APP_SECRET=${APP_SECRET}
        - DATABASE_URL=${DATABASE_URL}
      working_dir: "/var/www"
      deploy:
        resources:
          limits:
                memory: 100M
      depends_on:
        - db
###> doctrine/doctrine-bundle ###
    db:
      image: mysql:8.0
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
      ports:
        - "3306:3306"
      volumes:
        - "./.data/db:/var/lib/mysql"
      environment:
        - "MYSQL_ROOT_PASSWORD=123"
        - "MYSQL_USER=appuser"
        - "MYSQL_PASSWORD=userPass"
        - "MYSQL_DATABASE=app"
###< doctrine/doctrine-bundle ###

    mailcatcher:
      image: schickling/mailcatcher
      ports:
        - "1080:1080"
    
    whatsappapi:
      build:
        context: ./whatsapp-api
      environment: 
        - "DATABASE_CONNECTION_URI=mongodb://root:example@mongodb:27017/?authSource=admin&readPreference=primary&ssl=false&directConnection=true"
      ports: 
        - "8083:8083"
      volumes:
        - "./docker/whatsapp-api/instances:/home/api/instances"

    mongodb:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      ports:
        - "27017:27017"